services:
  mysql:
    image: mysql:8.0
    container_name: hosting_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panel
      MYSQL_USER: panel
      MYSQL_PASSWORD: panel
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  backend:
    build: ./backend
    container_name: hosting_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: mysql://panel:panel@mysql:3306/panel
      FRONTEND_URL: https://panel.velvacloud.com
      PORT: 4000
    depends_on:
      - mysql
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: hosting_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api
      PORT: 3000
    depends_on:
      - backend
    ports:
      - "3000:3000"

# Remove caddy here to avoid port 80/443 conflicts with your existing site.
# Configure your existing web server to reverse proxy the subdomain instead.

volumes:
  mysql_data: