services:
  mysql:
    image: mysql:8.0
    container_name: hosting_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panel
      MYSQL_USER: panel
      MYSQL_PASSWORD: panel
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -proot -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: hosting_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: mysql://panel:panel@mysql:3306/panel
      FRONTEND_URL: https://panel.velvacloud.com
      PORT: 4000
      SEED_ON_BOOT: "true"
      # PKI (persist CA so it doesn't regenerate on restart)
      CA_KEY_PATH: /app/certs/ca.key
      CA_CERT_PATH: /app/certs/ca.crt
      # mTLS (panel -> agent)
      DAEMON_CA: /app/certs/ca.crt
      DAEMON_CLIENT_CERT: /app/certs/panel.crt
      DAEMON_CLIENT_KEY: /app/certs/panel.key
      # Agent registration (local dev)
      NODE_REGISTRATION_SECRET: localdev
      AUTO_APPROVE_NODES: "true"
      # Agent URL inside compose network
      DAEMON_URL: https://daemon:9443
      # Auto-generate panel client cert if missing
      AUTO_GENERATE_PANEL_CERT: "true"
      # Development: allow CN/SAN hostname mismatch while CA is still enforced
      AGENT_SKIP_HOSTNAME_VERIFY: "true"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - type: bind
        source: ${PWD}/pki
        target: /app/certs
        read_only: false
    ports:
      - "4000:4000"
    healthcheck:
      # Use lightweight health endpoint rather than Swagger UI to reduce flakiness
      test: ["CMD-SHELL", "wget -qO- http://localhost:4000/api/status/system > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s

  frontend:
    build: ./frontend
    container_name: hosting_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api
      API_PROXY_TARGET: http://backend:4000
      PORT: 3000
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000 > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  daemon:
    build: ./daemon
    container_name: hosting_daemon
    restart: unless-stopped
    environment:
      # Point agent to panel API (inside compose network)
      PANEL_URL: http://backend:4000/api
      # Auto-bootstrap using static registration secret (matches backend)
      REGISTRATION_SECRET: localdev
      # Optional descriptive metadata
      NODE_NAME: local-node
      NODE_LOCATION: local
      # TLS output and listen port
      CERTS_DIR: /data/certs
      DAEMON_PORT: 9443
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - daemon_certs:/data/certs
      - /var/run/docker.sock:/var/run/docker.sock
    # Do not publish the daemon port to host to avoid conflicts.
    # The daemon only needs to reach the panel; inbound mTLS calls from panel
    # are not required in Phase 1–3.
    expose:
      - "9443"

# Remove caddy here to avoid port 80/443 conflicts with your existing site.
# Configure your existing web server to reverse proxy the subdomain instead.

volumes:
  mysql_data:
  daemon_certs: