version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: hosting_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panel
      MYSQL_USER: panel
      MYSQL_PASSWORD: panel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  # Redis reserved for future phases (rate limiting, queues)
  # redis:
  #   image: redis:7
  #   container_name: hosting_redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"

volumes:
  mysql_data: